### PR TITLE
Add 7-series rrgraph to CI

### PR DESCRIPTION
**Pull request by litghost**
Remaining tasks:
- [x] Wait for https://github.com/SymbiFlow/symbiflow-arch-defs/pull/538 to be merged
- [ ] Determine "-j<N>" level that enables acceptable run time.  Adding 7-series rrgraph import to CI will add ~30 minutes, which is likely too much

### CODE REVIEW

**Comment by litghost** [comment]
Current runtime before this PR: 37 min 27 sec

**Comment by elmsfu** [comment]
The [default tier](https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system) for travis is 2 CPUs, so not sure we will get much for higher than `-j 2`. see [travis makefile optimization](https://docs.travis-ci.com/user/speeding-up-the-build/#makefile-optimization)

**Comment by litghost** [comment]
> The [default tier](https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system) for travis is 2 CPUs, so not sure we will get much for higher than `-j 2`. see [travis makefile optimization](https://docs.travis-ci.com/user/speeding-up-the-build/#makefile-optimization)

I think trying for -j2 on the longer portions of the build is worth trying, under the assumption that the current CI run completes successfully.

**Comment by litghost** [comment]
Time limit 50 minutes, closing this.

**Comment by elmsfu** [comment]
I think that is per Travis job. We could look at splitting it up in different ways like a travis job per architecture. But it's probably not worth our time and should focus on running on a larger build server (ie kokoro).

**Pull request closed without merging**
