### PR TITLE
cmake: added --part argument to fasm2frames

### PR DESCRIPTION
**Pull request by acomodi**
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>

This PR is to fix an issue with fasm2frames, as now the tool needs to have the `--part` argument

### CODE REVIEW

**Comment by mkurc-ant** [comment]
The CI will fail due to a bug in `fasm2frames.py` related to ROI targets until #1181 is merged.
```
Traceback (most recent call last):
  File "/tmpfs/src/github/symbiflow-arch-defs/third_party/prjxray/utils/fasm2frames.py", line 293, in <module>
    main()
  File "/tmpfs/src/github/symbiflow-arch-defs/third_party/prjxray/utils/fasm2frames.py", line 289, in main
    emit_pudc_b_pullup=args.emit_pudc_b_pullup)
  File "/tmpfs/src/github/symbiflow-arch-defs/third_party/prjxray/utils/fasm2frames.py", line 162, in run
    extra_features += fasm.parse_fasm_string('\n'.join(required_features))
TypeError: unsupported operand type(s) for +=: 'generator' and 'generator'
```

**Comment by mithro** [comment]
@mkurc-ant Did you mean a different pull request? That one appears to already be merged?

**Comment by mkurc-ant** [comment]
@mithro Sorry, I meant https://github.com/SymbiFlow/prjxray/pull/1181 for prjxray.

**Comment by acomodi** [comment]
@mkurc-ant I see that https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1222 already adds the `--part` argument to fasm2frames. I believe this PR can be closed

**Comment by mkurc-ant** [comment]
@acomodi Depending which one we can merge first. If there is approval for #1222 then yes, we can close this one.

**Comment by acomodi** [comment]
The issue solved with this PR has been solved with https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1204. Closing

**Pull request closed without merging**
