### PR TITLE
fasm2bels: add --verbose to catch unknown bits

### PR DESCRIPTION
**Pull request by acomodi**
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>

### CODE REVIEW

**Comment by acomodi** [comment]
@litghost Vendor tools CI shows several tests failing for unknown bits. We should track them down and analyze locally what is happening.

**Comment by litghost** [comment]
> @litghost Vendor tools CI shows several tests failing for unknown bits. We should track them down and analyze locally what is happening.

Yes.  They all appear to be SERDES related bits.   I vaguely feel that @mkurc-ant might know about this?

**Comment by mkurc-ant** [comment]
I doubt that I'll have time to look into that this week.

For sure there are unknown IOB bits that emerge whenever internal VREF is not set and there is something that uses an IOSTANDARD requiring VREF. Meaning that those bits enable external VREF.

As for SERDES I'd need to revisit the fuzzer that I wrote for the ISERDES some time ago. I dropped its integration as it wasn't a priority.

**Comment by litghost** [comment]
FYI, fixing this should be part of the "getting ready for users" burndown.

**Comment by mkurc-ant** [comment]
I've created an issue with the list of the unknown bits and added it to the "getting ready for users" burndown list.

**Comment by mkurc-ant** [comment]
This is strange, When reproducing the problem these bits emerged even when converting a Symbiflow bitstream to fasm. But once I've re-tried that on the most recent Symbiflow master the problem was gone.

I suspect that the cause was some kind of bug in bittools that has already been fixed. I rebased the PR. Let's see how the CI goes.

**Comment by mkurc-ant** [comment]
I must have messed up something. Now I can reproduce the issue locally.

**Comment by mkurc-ant** [comment]
I've finished integration of the ISERDES fuzzer there: https://github.com/SymbiFlow/prjxray/pull/978 According to my local tests that allowed to get rid of at least some unknown bits.

**Pull request closed without merging**
