### PR TITLE
WIP: ROI breakout with new VtR version

### PR DESCRIPTION
**Pull request by acomodi**
This PR uses the new VtR version and is built on top of https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1090.

It also removes the GRAPH limit and adds also the `CLK_BUFG_TOP` tile

### CODE REVIEW

**Comment by acomodi** [comment]
I am running `picosoc` locally and it is taking a huge amount of time to route with the ROI-less full 50T. In addition there are errors during `check_rr_graph` related to the SING IOPADS:

```
Error 42: in check_rr_graph: node 1480345 (IPIN) at (147,108) block=BLK-TL-RIOPAD_SING side=RIGHT has no fanin.
Error 43: in check_rr_graph: node 1480346 (IPIN) at (147,108) block=BLK-TL-RIOPAD_SING side=RIGHT has no fanin.
Error 44: in check_rr_graph: node 1480347 (IPIN) at (147,108) block=BLK-TL-RIOPAD_SING side=RIGHT has no fanin.
Error 45: in check_rr_graph: node 1480381 (IPIN) at (147,108) block=BLK-TL-RIOPAD_SING side=TOP has no fanin.
Error 46: in check_rr_graph: node 1489270 (IPIN) at (147,159) block=BLK-TL-RIOPAD_SING side=TOP has no fanin.
Error 47: in check_rr_graph: node 1489271 (IPIN) at (147,159) block=BLK-TL-RIOPAD_SING side=RIGHT has no fanin.
Error 48: in check_rr_graph: node 1489272 (IPIN) at (147,159) block=BLK-TL-RIOPAD_SING side=RIGHT has no fanin.
Error 49: in check_rr_graph: node 1489273 (IPIN) at (147,159) block=BLK-TL-RIOPAD_SING side=RIGHT has no fanin.
Error 50: in check_rr_graph: node 1489307 (IPIN) at (147,159) block=BLK-TL-RIOPAD_SING side=TOP has no fanin.
Warning 106: in check_rr_graph: fringe node 2472997 CHANY at (96,27) has no fanin.
         This is possible on a fringe node based on low Fc_out, N, and certain lengths.
## Loading routing resource graph took 47.80 seconds (max_rss 11984.0 MiB, delta_rss +11853.5 MiB)
  RR Graph Nodes: 3537983
  RR Graph Edges: 22965763
# Create Device took 48.13 seconds (max_rss 11984.0 MiB, delta_rss +11853.5 MiB)

# Load Placement
# Load Placement took 0.31 seconds (max_rss 11984.0 MiB, delta_rss +0.0 MiB)

# Routing
  RR Graph Nodes: 3537983
  RR Graph Edges: 22965763
Confirming router algorithm: TIMING_DRIVEN.
---- ------ ------- ---- ------- ------- ------- ----------------- --------------- -------- ---------- ---------- ---------- ---------- --------
Iter   Time    pres  BBs    Heap  Re-Rtd  Re-Rtd Overused RR Nodes      Wirelength      CPD       sTNS       sWNS       hTNS       hWNS Est Succ
      (sec)     fac Updt    push    Nets   Conns                                       (ns)       (ns)       (ns)       (ns)       (ns)     Iter
---- ------ ------- ---- ------- ------- ------- ----------------- --------------- -------- ---------- ---------- ---------- ---------- --------
Warning 107: No routing path for connection to sink_rr 1077740, retrying with full device bounding box
Warning 108: 17 timing startpoints were not constrained during timing analysis
Warning 109: 123 timing endpoints were not constrained during timing analysis
   1 1014.4     0.0    0 5.1e+09    5623   16804   12573 ( 0.355%)  835995 ( 9.8%)   18.266     -2159.     -8.266      0.000      0.000      N/A
   2  542.6     0.5  107 3.0e+09    4510   14277   10313 ( 0.291%)  590059 ( 6.9%)   18.266     -2159.     -8.266     -127.7     -1.892      N/A
   3  723.8     0.6   60 4.1e+09    4333   13876    9986 ( 0.282%)  608607 ( 7.2%)   18.266     -2159.     -8.266     -977.9     -8.097      N/A
   4  883.2     0.8  114 4.9e+09    4253   13740    9510 ( 0.269%)  602971 ( 7.1%)   18.266     -2159.     -8.266     -564.4     -3.879      N/A
   5  973.4     1.1  146 5.4e+09    4092   13311    8268 ( 0.234%)  603829 ( 7.1%)   18.266     -2159.     -8.266     -514.6     -5.858      N/A
```

**Comment by litghost** [comment]
> there are errors during `check_rr_graph` related to the SING IOPADS

I'm not super worried about this error.

> I am running `picosoc` locally and it is taking a huge amount of time to route with the ROI-less full 50T

This is worrying.  The next step is to figure out how much time is it taking to route each net, and see if some nets are misbehaving.  For example, the presence of hold failures is likely a problem in the clock routing lookahead.

**Comment by litghost** [comment]
Yay!  https://source.cloud.google.com/results/invocations/2dfb957d-daa2-4b60-9c8a-aa7a2bf74d68/details completed successfully!  It took too long, but it finished successfully.

Notes:
 - picosoc only reached 40 MHz, :(
 - picosoc had hold violations :(
 - murax had hold violations :(

**Comment by acomodi** [comment]
Yep, those hold violations are indeed true, in fact both murax and picosoc do not work on HW.
On the other hand the counter test works on HW.

**Comment by litghost** [comment]
The hold violations on murax/picosoc were caused by a `BUFG` not being instanced.  I'm re-running murax now with a BUFG explicitly instanced, and checking if it is better.

If murax and picosoc are working with a BUFG, we can enable yosys BUFG insertion, which is currently disabled (https://github.com/SymbiFlow/symbiflow-arch-defs/blob/master/xc7/yosys/synth.tcl#L5).

**Comment by acomodi** [comment]
> If murax and picosoc are working with a BUFG, we can enable yosys BUFG insertion, which is currently disabled 

Shouldn't we first transition all the tests to a ROI-less full 50T architecture? I mean, if BUFG are instantiated by yosys automatically, the tests that are now ROI-dependent would fail as no BUFG primitive is available for them.

**Comment by litghost** [comment]
> > If murax and picosoc are working with a BUFG, we can enable yosys BUFG insertion, which is currently disabled
> 
> Shouldn't we first transition all the tests to a ROI-less full 50T architecture? I mean, if BUFG are instantiated by yosys automatically, the tests that are now ROI-dependent would fail as no BUFG primitive is available for them.

Agreed, but let's get the routing speed up first.

**Comment by litghost** [comment]
Superseded by #1105

**Pull request closed without merging**
