### PR TITLE
Update VtR

### PR DESCRIPTION
**Pull request by acomodi**
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>

This PR updates VTR to the latest conda version.

### CODE REVIEW

**Comment by mithro** [comment]
Looks like CI failed?

**Comment by acomodi** [comment]
@mithro Yes, Travis CI failed to find the latest conda-package of VTR which was correctly compiled in the latest update: https://travis-ci.com/SymbiFlow/conda-packages/jobs/238131054. I am trying to see what could cause this behavior.

**Comment by acomodi** [comment]
Here there's the error message:

```
WARNING: The --force flag will be removed in a future conda release.
         See 'conda install --help' for details about the --force-reinstall
         and --clobber flags.


Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - vtr==7.0.5_8325_g46b95c7e9=20190923_110951

Current channels:

  - https://conda.anaconda.org/symbiflow/linux-64
  - https://conda.anaconda.org/symbiflow/noarch
  - https://conda.anaconda.org/pkgw-forge/linux-64
  - https://conda.anaconda.org/pkgw-forge/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/m-labs/linux-64
  - https://conda.anaconda.org/m-labs/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


```

**Comment by mithro** [comment]
@acomodi That revision doesn't appear in the repo @ https://conda.anaconda.org/symbiflow/linux-64 - where did you get the value from?

**Comment by acomodi** [comment]
@mithro From the Travis CI build of conda: https://travis-ci.com/SymbiFlow/conda-packages/jobs/238131054

**Comment by acomodi** [comment]
Closing this PR as it needs the `tile` tags to successfully build. Including VtR update in: https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1017

**Pull request closed without merging**
