### PR TITLE
[WIP]: Update VTR with upstream patches.

### PR DESCRIPTION
**Pull request by litghost**

### CODE REVIEW

**Comment by litghost** [comment]
Waiting for green CI

**Comment by acomodi** [comment]
Looks like something was introduced in VTR that breaks routing for Lattice.

```
 480    0.0 1.0e+25    0   61388       2       8       1 ( 0.000%)   94596 (27.1%) 141000000000.000 -7.490e+13 -141000000000.000 -2.694e+12 -102000000000.000      N/A
 481    0.0 1.0e+25    0   46663       1       6       1 ( 0.000%)   94639 (27.1%) 141000000000.000 -7.491e+13 -141000000000.000 -2.694e+12 -102000000000.000      N/A
 482    0.0 1.0e+25    0  138011       2       3       1 ( 0.000%)   94664 (27.2%) 141000000000.000 -7.491e+13 -141000000000.000 -2.694e+12 -102000000000.000      N/A
 483    0.1 1.0e+25    0  231777       4       6       1 ( 0.000%)   94632 (27.1%) 141000000000.000 -7.491e+13 -141000000000.000 -2.694e+12 -102000000000.000      N/A
 484    0.0 1.0e+25    0  172742       3       6       1 ( 0.000%)   94614 (27.1%) 141000000000.000 -7.491e+13 -141000000000.000 -2.694e+12 -102000000000.000      N/A
 485    0.0 1.0e+25    0   47486       1       4       1 ( 0.000%)   94639 (27.1%) 141000000000.000 -7.491e+13 -141000000000.000 -2.694e+12 -102000000000.000      N/A
 486    0.0 1.0e+25    0   45625       1       7       1 ( 0.000%)   94670 (27.2%) 141000000000.000 -7.492e+13 -141000000000.000 -2.694e+12 -102000000000.000      N/A
 487    0.0 1.0e+25    0  138168       2       3       1 ( 0.000%)   94664 (27.2%) 141000000000.000 -7.492e+13 -141000000000.000 -2.694e+12 -102000000000.000      N/A
 488    0.0 1.0e+25    0   39570       1       4       1 ( 0.000%)   94666 (27.2%) 141000000000.000 -7.492e+13 -141000000000.000 -2.694e+12 -102000000000.000      N/A
 489    0.0 1.0e+25    0  135879       3       5       1 ( 0.000%)   94651 (27.1%) 141000000000.000 -7.498e+13 -141000000000.000 -2.694e+12 -102000000000.000      N/A
 490    0.0 1.0e+25    0   20116       1       2       1 ( 0.000%)   94644 (27.1%) 141000000000.000 -7.493e+13 -141000000000.000 -2.694e+12 -102000000000.000      N/A
 491    0.0 1.0e+25    1   62215       2       7       1 ( 0.000%)   94621 (27.1%) 141000000000.000 -7.492e+13 -141000000000.000 -2.694e+12 -102000000000.000      N/A
 492    0.0 1.0e+25    0  132560       2       5       1 ( 0.000%)   94616 (27.1%) 141000000000.000 -7.492e+13 -141000000000.000 -2.694e+12 -102000000000.000      N/A
 493    0.0 1.0e+25    0   59322       2       5       1 ( 0.000%)   94613 (27.1%) 141000000000.000 -7.492e+13 -141000000000.000 -2.694e+12 -102000000000.000      N/A
 494    0.0 1.0e+25    0   59356       2       5       1 ( 0.000%)   94616 (27.1%) 141000000000.000 -7.492e+13 -141000000000.000 -2.694e+12 -102000000000.000      N/A
 495    0.0 1.0e+25    0  105201       3      12       1 ( 0.000%)   94591 (27.1%) 141000000000.000 -7.494e+13 -141000000000.000 -2.694e+12 -102000000000.000      N/A
 496    0.0 1.0e+25    1   77563       1       1       1 ( 0.000%)   94630 (27.1%) 141000000000.000 -7.494e+13 -141000000000.000 -2.694e+12 -102000000000.000      N/A
 497    0.0 1.0e+25    0   59263       2       5       1 ( 0.000%)   94635 (27.1%) 141000000000.000 -7.492e+13 -141000000000.000 -2.694e+12 -102000000000.000      N/A
 498    0.0 1.0e+25    0  171190       2       2       1 ( 0.000%)   94672 (27.2%) 141000000000.000 -7.492e+13 -141000000000.000 -2.694e+12 -102000000000.000      N/A
 499    0.0 1.0e+25    0  145389       2       5       1 ( 0.000%)   94653 (27.1%) 141000000000.000 -7.492e+13 -141000000000.000 -2.694e+12 -102000000000.000      N/A
 500    0.0 1.0e+25    0  115124       3      12       1 ( 0.000%)   94582 (27.1%) 141000000000.000 -7.492e+13 -141000000000.000 -2.694e+12 -102000000000.000      N/A
Routing failed.
Router Stats: total_nets_routed: 10338 total_connections_routed: 34798 total_heap_pushes: 68581875 total_heap_pops: 53217388
# Routing took 28.33 seconds (max_rss 3196.8 MiB, delta_rss +8.0 MiB)
Circuit is unroutable with a channel width factor of 100.
VPR failed to implement circuit
The entire flow of VPR took 35.77 seconds (max_rss 3196.8 MiB)
tests/9-soc/murax/CMakeFiles/murax_bin.dir/build.make:86: recipe for target 'tests/9-soc/murax/murax/ice40-top-routing-virt-hx8k-ct256/toplevel.route' failed
make[3]: *** [tests/9-soc/murax/murax/ice40-top-routing-virt-hx8k-ct256/toplevel.route] Error 2
CMakeFiles/Makefile2:202780: recipe for target 'tests/9-soc/murax/CMakeFiles/murax_bin.dir/all' failed
make[2]: *** [tests/9-soc/murax/CMakeFiles/murax_bin.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
```

**Comment by acomodi** [comment]
@litghost Apparently we have a non-deterministic behavior. Lattice compiles now

**Comment by litghost** [comment]
> @litghost Apparently we have a non-deterministic behavior. Lattice compiles now

It is probably worth going back and checking if the non-determinism existed before.

**Comment by acomodi** [comment]
@litghost Agreed, I am running `git bisect` also on arch-defs from this PR commit (I'll run murax build multiple times)

**Comment by acomodi** [comment]
Murax on ice40  seems to be stable in previous versions. Each bisect step successfully compiled 10 times. I have started another CI build and local builds to see if the failure was an isolated symptom.

**Comment by acomodi** [comment]
@litghost I have forced three runs after the failure an it seems that the issue with ice40 is not showing up anymore.

**Pull request closed without merging**
