### PR TITLE
Add ANTLR4 dependencies for fasm.

### PR DESCRIPTION
**Pull request by HackerFoo**

### CODE REVIEW

**Comment by litghost** [comment]
```
========================================
Host install packages
----------------------------------------
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libantlr4-runtime-dev
```

**Comment by litghost** [comment]
I don't believe build the antlr4 runtime within the arch-defs CI is the right approach here, especially given the fact that 4 other repos will need to do the same thing.  I think using a PPA to get a package or adding the dep to the litex hub conda misc are better approaches. @mithro, thoughts?

**Comment by HackerFoo** [comment]
This is a temporary fix until we have a proper package. It doesn't take long to build.

**Comment by litghost** [comment]
> This is a temporary fix until we have a proper package. It doesn't take long to build.

You would have to add this temporary fix to 5 build systems, so even if it doesn't take a long time, it like a bad approach.

**Comment by HackerFoo** [comment]
I think this is a better solution: https://github.com/SymbiFlow/fasm/pull/41

**Comment by HackerFoo** [comment]
Superseded by https://github.com/SymbiFlow/fasm/pull/41

**Pull request closed without merging**
