### PR TITLE
PEP8:  Reorder imports, whitespace, rename shadowed names

### PR DESCRIPTION
**Pull request by Cabalist**
This is in response to #13 

There are a few more issues with this file that I thought I should point out.  

1) It is my understanding that `ArgumentParser.add_argument()` doesn't return anything but it is used to assign to `parser.name_inputs` and `parser.name_selects`  I could be wrong and there may be some functionality I am not aware of.

2) On line 362 `width` & `name` is used outside of a for loop.  This can do unexpected things but will crash if `port_names` is empty.

2a) `subckt` also might be undefined but that is dependent on if there are args.type besides `logic` and `routing`.

3) There are is some unused code in this file:
[call_args](https://github.com/SymbiFlow/symbiflow-arch-defs/compare/master...Cabalist:master#diff-34e17609f3f75c0be9c4fadf8da04f46R126)
[buf_dir](https://github.com/SymbiFlow/symbiflow-arch-defs/compare/master...Cabalist:master#diff-34e17609f3f75c0be9c4fadf8da04f46R159)
[mux_mk](https://github.com/SymbiFlow/symbiflow-arch-defs/compare/master...Cabalist:master#diff-34e17609f3f75c0be9c4fadf8da04f46R160)
[remove_files](https://github.com/SymbiFlow/symbiflow-arch-defs/compare/master...Cabalist:master#diff-34e17609f3f75c0be9c4fadf8da04f46R218)
[defs](https://github.com/SymbiFlow/symbiflow-arch-defs/compare/master...Cabalist:master#diff-34e17609f3f75c0be9c4fadf8da04f46R306)
[mux_prefix](https://github.com/SymbiFlow/symbiflow-arch-defs/compare/master...Cabalist:master#diff-34e17609f3f75c0be9c4fadf8da04f46R316)
All of these look like they could be removed.

### CODE REVIEW

**Comment by mithro** [comment]
Hi,

Thank you for sending the pull request! It's awesome to see you contributing to this project. However, before I can look at this request you need to add [DCO sign-off](https://developercertificate.org/) to commits in this repository.

We require [DCO sign-off](https://developercertificate.org/) for **all** commits to this repository (including all authors). Please see the [following URL](https://github.com/probot/dco#how-it-works) to see more information and BeeWare also have a [Beginners guide to DCOs](https://pybee.org/contributing/how/dco/).

You can use `git commit --amend --signoff` and then a `git push --force` to add the signoff. You can also use `git rebase --signoff`.

Thanks!

**Comment by mithro** [comment]
Thank you! - Like your changes like `type` -> `pin_type`.

However, it seems that [`yapf`](https://github.com/google/yapf) seems to disagree with some of your changes but I thought we had configured it for `PEP8` mode. You can see the changes by running `make format` inside the `utils` directory. Would you mind taking a look at if we have configured `yapf` wrong?

**Comment by Cabalist** [comment]
Will do.   It looks like some the changes are fairly opinion based but I would say I prefer the first version over the second.  It is wrapping it because the line length is 81.  

Pull Request version:
```python
args.name_inputs = [args.name_input + str(i) for i in range(args.width)]
```

Yapf version:
```python
args.name_inputs = [
    args.name_input + str(i) for i in range(args.width)
]
```

I'd argue a softer line limit would be beneficial.

**Comment by Cabalist** [comment]
The other big one is "continuation indent":  https://www.python.org/dev/peps/pep-0008/#indentation

Specifically "More indentation included to distinguish this from the rest." I have mine set to 8 spaces.  

In my own code I like the "Aligned with opening delimiter." example.

**Comment by mithro** [comment]
@Cabalist I have no strong opinion on which is better and happy to go with either - just want to make sure the automated tools are producing the correct result.

**Comment by mithro** [comment]
@Cabalist - FYI - I've merged #115 which I wanted to do before merging this change. If you can resolve the `yapf` and `pep8` differences I would love to merge it!

**Comment by Cabalist** [comment]
@mithro No problem!  Is your preferred change to a `yapf` config file or to the formatting of the code to match the current `yapf` settings?  

I can't seem to find the yapf config in this repo.   I could be missing something obvious but I usually look for  `[style]` heading somewhere.

**Comment by mithro** [comment]
@Cabalist Whatever you can make it work easily and matches PEP8.

**Comment by mithro** [comment]
@Cabalist Sorry about taking long time to reply, been a busy week. 

The idea with yapf is that we don't have to think :-) -- You just run it and everything becomes the right format. Think `gofmt` or `clang-format`.

> Most of the current formatters for Python --- e.g., autopep8, and pep8ify ---
> are made to remove lint errors from code. This has some obvious limitations.
> For instance, code that conforms to the PEP 8 guidelines may not be
> reformatted.  But it doesn't mean that the code looks good.
> 
> YAPF takes a different approach. It's based off of 'clang-format', developed by
> Daniel Jasper. In essence, the algorithm takes the code and reformats it to the
> best formatting that conforms to the style guide, even if the original code
> didn't violate the style guide. The idea is also similar to the 'gofmt' tool for
> the Go programming language: end all holy wars about formatting - if the whole
> codebase of a project is simply piped through YAPF whenever modifications are
> made, the style remains consistent throughout the project and there's no point
> arguing about style in every code review.
> 
> The ultimate goal is that the code YAPF produces is as good as the code that a
> programmer would write if they were following the style guide. It takes away
> some of the drudgery of maintaining your code.

**Comment by mithro** [comment]
Hi @Cabalist,

I've rebased this change onto the latest master, can you take a look over it and see if you think it still makes sense to be merged?

Thanks!

**Pull request closed without merging**
