### PR TITLE
Add utilities for print override delay matrix and connection box lookahead

### PR DESCRIPTION
**Pull request by litghost**

### CODE REVIEW

**Comment by litghost** [comment]
> Could it be worth adding CMake targets to run these utilities automatically and output debug files?
> 
> CI failed with the following Icarus error (never seen before):

I've been tracking the failure, it looks like a depedency or file collision failure.  Unrelated to this PR.

**Comment by litghost** [comment]
> CI failed with the following Icarus error (never seen before):

I've been able to replicate this on the large symbiflow VM.  I believe this may be related to the VM change (med to large) we tried this week.

**Comment by litghost** [comment]
> Could it be worth adding CMake targets to run these utilities automatically and output debug files?

The capnp files are located in the VTR repo, which is not currently imported.   I'm hesistent to do that right now just for this tool.

**Comment by mithro** [comment]
Should we update the conda package to include the capnp files?

**Comment by litghost** [comment]
> Should we update the conda package to include the capnp files?

That will be required when/if we write the routing graph directly as capnp.  So yes?

**Pull request merged**
