### PR TITLE
Bootstrapping Sphinx documentation for the project.

### PR DESCRIPTION
**Pull request by yusufm**
Generate HTML doc by running:

  cd docs
  make html

### CODE REVIEW

**Comment by yusufm** [comment]
Travis failures do not seem related to these changes which are isolated to the docs/ dir.

**Comment by yusufm** [comment]
Example of ReadTheDocs auto generated site (from my forked repo) here:

https://symbiflow-arch-defs-sphinxtest.readthedocs.io/en/latest/

**Comment by elmsfu** [comment]
@yusufm Thanks for the PR! Before we review it, please add a DCO sign-off. We'll look into the travis failure.

You can use `git commit --amend --signoff` or `git rebase --signoff` and then a `git push --force` to add it.

We require [DCO sign-off](https://developercertificate.org/) for all commits. Please see [here](https://github.com/probot/dco#how-it-works) for more information or [BeeWare's guide](https://pybee.org/contributing/how/dco/)

**Comment by yusufm** [comment]
Signed the DCO.

**Comment by mithro** [comment]
LGTM.

Merging.

**Comment by mithro** [comment]
@yusufm Thanks for sending this! Did you see my previously open "work in progress" pull request for this at https://github.com/SymbiFlow/symbiflow-arch-defs/pull/44 ?

One of the goals was to use breathe + DoxygenVerilog to generate documentation from the `.sim.v` files. Are you interested in taking a look at that further?

**Comment by yusufm** [comment]
@mithro Sure, I'll take a look at adding breathe and DoxygenVerilog.

**Comment by mithro** [comment]
@yusufm - [symbolator](https://kevinpt.github.io/symbolator/) also has a [sphinx extension](https://kevinpt.github.io/symbolator/#sphinx-extension). It would be awesome if we could generate symbols for the `xxx.sim.v` files using it.

```rst
.. symbolator::
  :alt: Alt text
  :align: center
  :caption: Caption text
  :symbolator_cmd: /usr/local/bin/symbolator
  :name: vlog-example

  module vlog
    (foo, bar);

    input wire foo;
    output reg bar;
  endmodule;
```

**Comment by yusufm** [comment]
> @yusufm - [symbolator](https://kevinpt.github.io/symbolator/) also has a [sphinx extension](https://kevinpt.github.io/symbolator/#sphinx-extension). It would be awesome if we could generate symbols for the `xxx.sim.v` files using it.
> 
> ```
> .. symbolator::
>   :alt: Alt text
>   :align: center
>   :caption: Caption text
>   :symbolator_cmd: /usr/local/bin/symbolator
>   :name: vlog-example
> 
>   module vlog
>     (foo, bar);
> 
>     input wire foo;
>     output reg bar;
>   endmodule;
> ```

I got the symbolator extension working locally, but there are issues with installing the necessary dependencies on readthedocs. If you have any idea about how to resolve those, let me know.

**Comment by mithro** [comment]
What is the missing dependencies?

I believe that readthedocs can install via conda? See https://docs.readthedocs.io/en/latest/conda.html and our packages at https://github.com/SymbiFlow/conda-packages

Another option is to put things into a wheel?

**Pull request merged**
