### PR TITLE
WIP: Use "buffer" switch type for non-configurable switches (e.g. ppips).

### PR DESCRIPTION
**Pull request by litghost**
This is part 1 of #1019

### CODE REVIEW

**Comment by acomodi** [comment]
@litghost: I am trying to get this to work.

I have locally fixed VTR to accepct Cinternal on buffer switches, but it fails now with the following error:
```
Type: Routing
File: /home/alessandro/projects/symbiflow/vtr-symbiflow/vpr/src/route/check_rr_graph.cpp
Line: 546
Message: Non-configurable BUFFER type switch must have only one driver.  Actual fan-in was 2 (expected 1).
  Possible cause is complex block output pins connecting to:
    RR node: 12223 type: CHANX location: (7,8) <-> (9,8) track: 826 len: 2 longline: 0 seg_type: OUTPINFEED dir: BI_DIR capacity: 1
```

This because, apparently, `buffer` type switches must be unidirectional for VPR.

I am unsure whether this is something to be solved in this PR or in VPR.

**Comment by litghost** [comment]
> 
> 
> @litghost: I am trying to get this to work.
> 
> I have locally fixed VTR to accepct Cinternal on buffer switches, but it fails now with the following error:
> 
> ```
> Type: Routing
> File: /home/alessandro/projects/symbiflow/vtr-symbiflow/vpr/src/route/check_rr_graph.cpp
> Line: 546
> Message: Non-configurable BUFFER type switch must have only one driver.  Actual fan-in was 2 (expected 1).
>   Possible cause is complex block output pins connecting to:
>     RR node: 12223 type: CHANX location: (7,8) <-> (9,8) track: 826 len: 2 longline: 0 seg_type: OUTPINFEED dir: BI_DIR capacity: 1
> ```
> 
> This because, apparently, `buffer` type switches must be unidirectional for VPR.
> 
> I am unsure whether this is something to be solved in this PR or in VPR.

Ah, I think I remember this now.  So this is a bug (I believe) in check rr graph.  Basically, the fan in edge in this case is part of a short.

So the structure looks like:
```
CHAN -> buffer -> CHAN <- short -> CHAN
```
Check route has no valid solution to this configuration.  A short requires bidirectional edges, and buffer requires fan in = 1.  Double check that I'm remembering this correctly, and file a bug upstream.

**Comment by litghost** [comment]
@acomodi In the short term, just disable check rr route when generating the lookahead.  We already disable it during P&R to save time.

**Comment by acomodi** [comment]
@litghost All clear, thanks.

**Pull request closed without merging**
