### PR TITLE
WIP: Add picosoc test for nexys-video board.

### PR DESCRIPTION
**Pull request by litghost**

### CODE REVIEW

**Comment by acomodi** [comment]
```
  Netlist Clock '$abc$34054$auto$iopadmap.cc:361:execute$32560' Fanout: 1 pins (0.0%), 1 blocks (0.0%)
  Netlist Clock Error 1:
Type: SDC file
File: /tmpfs/src/github/symbiflow-arch-defs-presubmit-xc7a200t/build/tests/9-soc/picosoc/basys3.sdc
Line: 1
Message: Clock name or pattern 'clk' does not correspond to any nets. To create a virtual clock, use the '-name' option.
```

As the input clock name gets changed, there is a need of an explicit IBUF to caputure the clock, the output of the IBUF will have a human-readable name to be used in the SDC.

**Comment by litghost** [comment]
Local testing has identified some data missing from the A200T tilegrid.  I'll investigate today and hopefully push a fix to prjxray soon.

**Comment by litghost** [comment]
So tilegrid report shows that there are handful of INT_L/R tiles missing base addresses, and 2 HCLK_L and 2 HCLK_R tiles missing base addresses.
```
python3 utils/tilegrid_report.py
BRAM_L: 205/205 (100.00 %)
BRAM_R: 160/160 (100.00 %)
CFG_CENTER_BOT: 0/1 (0.00 %)
CFG_CENTER_MID: 1/1 (100.00 %)
CFG_CENTER_TOP: 0/1 (0.00 %)
CLBLL_L: 2525/2525 (100.00 %)
CLBLL_R: 2650/2650 (100.00 %)
CLBLM_L: 5800/5800 (100.00 %)
CLBLM_R: 5750/5750 (100.00 %)
CLK_BUFG_BOT_R: 1/1 (100.00 %)
CLK_BUFG_REBUF: 10/10 (100.00 %)
CLK_BUFG_TOP_R: 1/1 (100.00 %)
CLK_HROW_BOT_R: 3/3 (100.00 %)
CLK_HROW_TOP_R: 2/2 (100.00 %)
CLK_PMV2: 0/1 (0.00 %)
CMT_FIFO_L: 0/20 (0.00 %)
CMT_FIFO_R: 0/20 (0.00 %)
CMT_TOP_L_LOWER_B: 5/5 (100.00 %)
CMT_TOP_L_LOWER_T: 0/5 (0.00 %)
CMT_TOP_L_UPPER_B: 0/5 (0.00 %)
CMT_TOP_L_UPPER_T: 5/5 (100.00 %)
CMT_TOP_R_LOWER_B: 5/5 (100.00 %)
CMT_TOP_R_LOWER_T: 0/5 (0.00 %)
CMT_TOP_R_UPPER_B: 0/5 (0.00 %)
CMT_TOP_R_UPPER_T: 5/5 (100.00 %)
DSP_L: 160/160 (100.00 %)
DSP_R: 210/210 (100.00 %)
GTP_CHANNEL_0_MID_LEFT: 0/2 (0.00 %)
GTP_CHANNEL_0_MID_RIGHT: 0/2 (0.00 %)
GTP_CHANNEL_1_MID_LEFT: 0/2 (0.00 %)
GTP_CHANNEL_1_MID_RIGHT: 0/2 (0.00 %)
GTP_CHANNEL_2_MID_LEFT: 0/2 (0.00 %)
GTP_CHANNEL_2_MID_RIGHT: 0/2 (0.00 %)
GTP_CHANNEL_3_MID_LEFT: 0/2 (0.00 %)
GTP_CHANNEL_3_MID_RIGHT: 0/2 (0.00 %)
GTP_COMMON_MID_LEFT: 0/2 (0.00 %)
GTP_COMMON_MID_RIGHT: 0/2 (0.00 %)
HCLK_CMT: 5/5 (100.00 %)
HCLK_CMT_L: 5/5 (100.00 %)
HCLK_IOI3: 10/10 (100.00 %)
HCLK_L: 220/222 (99.10 %)
HCLK_L_BOT_UTURN: 1/1 (100.00 %)
HCLK_R: 220/222 (99.10 %)
HCLK_R_BOT_UTURN: 1/1 (100.00 %)
INT_L: 11025/11125 (99.10 %)
INT_R: 11025/11125 (99.10 %)
LIOB33: 120/120 (100.00 %)
LIOB33_SING: 10/10 (100.00 %)
LIOI3: 90/90 (100.00 %)
LIOI3_SING: 10/10 (100.00 %)
LIOI3_TBYTESRC: 20/20 (100.00 %)
LIOI3_TBYTETERM: 10/10 (100.00 %)
MONITOR_BOT: 1/1 (100.00 %)
MONITOR_MID: 0/1 (0.00 %)
MONITOR_TOP: 0/1 (0.00 %)
PCIE_BOT: 0/1 (0.00 %)
PCIE_TOP: 0/1 (0.00 %)
RIOB33: 120/120 (100.00 %)
RIOB33_SING: 10/10 (100.00 %)
RIOI3: 90/90 (100.00 %)
RIOI3_SING: 10/10 (100.00 %)
RIOI3_TBYTESRC: 20/20 (100.00 %)
RIOI3_TBYTETERM: 10/10 (100.00 %)
```

The missing columns are the INT/HCLK column:
 - HCLK_L_X136Y234
 - HCLK_R_X137Y234
 - HCLK_L_X136Y26
 - HCLK_R_X137Y26

These column correspond to the two INT/HCLK columns next to some hard blocks.  There was some code to handle these kind of cases in 005-tilegrid, but clearly it missed these columns.

**Comment by litghost** [comment]
PR has been updated with fixed A200T tilegrid, hopefully will go green now.

**Comment by litghost** [comment]
In order to fix the vendor tool tests, we need to propagate the default PROHIBIT setting and avoid letting VPR place here.

**Comment by litghost** [comment]
> In order to fix the vendor tool tests, we need to propagate the default PROHIBIT setting and avoid letting VPR place here.

@mithro I'm working on a PR to add the prohibits sites to tile grid.

**Pull request closed without merging**
