### PR TITLE
Add support for reading files using uhdm-plugin

### PR DESCRIPTION
**Pull request by kamilrakoczy**
This PR extends ``symbiflow_synth`` wrapper giving option to read input files using Surelog/UHDM with uhdm-plugin.

Signed-off-by: Kamil Rakoczy <krakoczy@antmicro.com>

### CODE REVIEW

**Review by acomodi — APPROVED** [review]
LGTM, let's wait for CI

**Comment by kgugala** [comment]
kokoro seem to be stuck?

**Comment by acomodi** [comment]
@mithro @tcal-x The Series7 Install CI keeps failing for some reason, but no log is produced (https://source.cloud.google.com/results/invocations/ff5be56a-37b7-4ec2-a8bc-e623be16f6b2). Is there a way to get the log?

**Comment by mithro** [comment]
Any reason this hasn't moved to the GitHub Actions Custom Runners that would let you debug this yourself?

**Comment by mithro** [comment]
```
Warnings: 4 unique messages, 5 total
End of script. Logfile hash: c6d6ef7d16, CPU: user 14.24s system 0.64s, MEM: 447.32 MB peak
Yosys 0.12+30 (git sha1 ed4642e18, x86_64-conda_cos6-linux-gnu-gcc 1.24.0.133_b0863d8_dirty -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/home/runner/work/conda-eda/conda-eda/workdir/conda-env/conda-bld/yosys_1639696247791/work=/usr/local/src/conda/yosys-0.12_36_ged4642e18 -fdebug-prefix-map=/tmpfs/src/github/symbiflow-arch-defs-presubmit-install/env/conda/envs/symbiflow_arch_def_base=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants)
Time spent: 49% 45x read_verilog (7 sec), 9% 14x design (1 sec), ...

 /----------------------------------------------------------------------------\
 |                                                                            |
 |  yosys -- Yosys Open SYnthesis Suite                                       |
 |                                                                            |
 |  Copyright (C) 2012 - 2020  Claire Xenia Wolf <claire@yosyshq.com>         |
 |                                                                            |
 |  Permission to use, copy, modify, and/or distribute this software for any  |
 |  purpose with or without fee is hereby granted, provided that the above    |
 |  copyright notice and this permission notice appear in all copies.         |
 |                                                                            |
 |  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES  |
 |  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF          |
 |  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR   |
 |  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES    |
 |  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN     |
 |  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF   |
 |  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.            |
 |                                                                            |
 \----------------------------------------------------------------------------/

 Yosys 0.12+30 (git sha1 ed4642e18, x86_64-conda_cos6-linux-gnu-gcc 1.24.0.133_b0863d8_dirty -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/home/runner/work/conda-eda/conda-eda/workdir/conda-env/conda-bld/yosys_1639696247791/work=/usr/local/src/conda/yosys-0.12_36_ged4642e18 -fdebug-prefix-map=/tmpfs/src/github/symbiflow-arch-defs-presubmit-install/env/conda/envs/symbiflow_arch_def_base=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants)


-- Running command `read_json top_io.json; tcl /tmpfs/src/github/symbiflow-arch-defs-presubmit-install/install/share/symbiflow/scripts/xc7/conv.tcl' --

1. Executing JSON frontend.
ERROR: Unexpected character in JSON file: 'make: *** [Makefile:24: build_arty-100t/top.eblif] Error 1

5/6 Test #4: binary_toolchain_test_xc7_50t_surelog ....   Passed   85.60 sec
6/6 Test #5: binary_toolchain_test_xc7_100t_surelog ...   Passed  129.99 sec

33% tests passed, 4 tests failed out of 6

Total Test time (real) = 130.04 sec

The following tests FAILED:
	  1 - binary_toolchain_test_xc7_50t (Failed)
	  2 - binary_toolchain_test_xc7_100t (Failed)
	  3 - binary_toolchain_test_xc7_200t (Failed)
	  6 - binary_toolchain_test_xc7_200t_surelog (Failed)
Errors while running CTest


[ID: 7044838] Build finished after 16607 secs, exit value: 1


Warning: Permanently added 'localhost' (ED25519) to the list of known hosts.

Warning: Permanently added 'localhost' (ED25519) to the list of known hosts.

[20:09:56] Loading Log4j Scanner Binary onto Build VM
[20:09:57] Loading Log4j Scanner Wrapper Script onto Build VM
[20:09:58] Running Scanner on VM.



[ID: 3811518] Executing command via SSH:
export KOKORO_BUILD_NUMBER="2213"
export KOKORO_JOB_NAME="foss-fpga-tools/symbiflow-arch-defs/presubmit/install"
source "$HOME/.kokoro_python_vars" ; "$KOKORO_PYTHON_COMMAND" /tmpfs/log4j_scanner.py

Found no vulnerable JARs.


[ID: 3811518] Build finished after 44 secs, exit value: 0


Warning: Permanently added 'localhost' (ED25519) to the list of known hosts.

[21:14:14] Executor 463856455 is unresponsive. Build terminated.
```

**Comment by mithro** [comment]
`[21:14:14] Executor 463856455 is unresponsive. Build terminated.` generally occurs when the number of files to upload ends up being to big...

**Comment by acomodi** [comment]
@mithro Thanks for the logs, anyhow yeah, we'll soon create a parallel GH action runner CI, and similarly to fpga-tool-perf verify that everything is stable before removing kokoro.

**Pull request merged**
