### PR TITLE
Update VTR

### PR DESCRIPTION
**Pull request by acomodi**
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>

### CODE REVIEW

**Comment by acomodi** [comment]
Travis CI failed with the following message:
```
The job exceeded the maximum time limit for jobs, and has been terminated.
```

I need to investigate what went wrong (there have been changes in VPR which could affect symbiflow tests, I have tested with `all_xc7` and `all_ice40` and it seemed to take a reasonable amount of time to complete).

**Comment by mithro** [comment]
@acomodi - Just started a rety of the Travis build to see if it was a transient problem or not...

**Comment by acomodi** [comment]
@mithro Ok, I have also ran `make all_route_tests`, which is the most time consuming step, locally and it completed in much less than the 50 minutes timeout limit.

**Comment by acomodi** [comment]
@mithro Travis went green, I suppose it was a transient issue

**Pull request merged**
