### PR TITLE
Add initial support for PULLTYPE.

### LINKED ISSUE #1314: Add support for PULLTYPE
There is no current support for PULLTYPEs, which are critical to have IOBs correctly working on HW. It is necessary to set the correct PULLTYPE features for different IOB working modes to have the desired effects on HW.

This issue should be solved, as it was generating problems further explained in [this comment](https://github.com/SymbiFlow/symbiflow-arch-defs/issues/1301#issuecomment-586594308).

### PR DESCRIPTION
**Pull request by litghost**
Fixes #1314

### CODE REVIEW

**Comment by mkurc-ant** [comment]
@litghost I'm unsure whether the PULLTYPE parameter is recognized by Vivado. If no then please add a comment that it is not as it is done with the IN_TERM parameter.

**Comment by litghost** [comment]
Its definitely accepted as a port property (https://github.com/SymbiFlow/prjxray/blob/09ae020ab35ec0bccf82440863481f23c9143a89/fuzzers/030-iob/generate.tcl#L63), unclear about a driver property.

**Comment by litghost** [comment]
> @litghost I'm unsure whether the PULLTYPE parameter is recognized by Vivado. If no then please add a comment that it is not as it is done with the IN_TERM parameter.

Sure fixed.

**Comment by mkurc-ant** [comment]
LGTM

**Comment by mkurc-ant** [comment]
LGTM

**Comment by mkurc-ant** [comment]
LGTM

**Pull request merged**
