### PR TITLE
Add utilities for parsing VPR route files.

### PR DESCRIPTION
**Pull request by litghost**
This begins to address #578 by providing a mapping from wire_pkey back
to VPR net name.

### CODE REVIEW

**Comment by mithro** [comment]
Not blocking merging this, but FYI - [PRGA](https://prga.readthedocs.io) should also have a Python parsers for VPRs output files. We should collaborate with them on that....

**Comment by litghost** [comment]
> Not blocking merging this, but FYI - [PRGA](https://prga.readthedocs.io) should also have a Python parsers for VPRs output files. We should collaborate with them on that....

Ah, sure.  This parse is kind of single purpose.  I think replacing this with duck2's summer work is probably the right long term plan, and PRGA can use that once it is ready.

**Comment by mithro** [comment]
@litghost Yeah - @duck2's work should make this all much easier!

**Comment by litghost** [comment]
People aren't reviewing this, so just addressing review in https://github.com/SymbiFlow/symbiflow-arch-defs/pull/586

**Pull request closed without merging**
