### PR TITLE
Use upstream packages directly

### PR DESCRIPTION
**Pull request by litghost**

### CODE REVIEW

**Review by mithro — APPROVED** [review]
LGTM

**Comment by mithro** [comment]
Failing CI?

**Comment by litghost** [comment]
> Failing CI?

Looks like kokoro glitched hard.  Almost like someone cancelled a bunch of jobs manually.

**Comment by litghost** [comment]
> > Failing CI?
> 
> Looks like kokoro glitched hard. Almost like someone cancelled a bunch of jobs manually.

I've restarted kokoro, we'll see if it glitches again.

**Review by acomodi — APPROVED** [review]
LGTM. Great to see that every CI went green using upstream packages for vtr and yosys!

**Comment by litghost** [comment]
> LGTM. Great to see that every CI went green using upstream packages for vtr and yosys!

Has fpga-tool-perf ingested the tarball from a345ef84f06a1fdb1a6016d39c8b3d1c3c6c064e and generated results?  I want to wait for a baseline from fpga-tool-perf before merging this.

**Comment by acomodi** [comment]
There is a PR in tool perf that enabled grabbing the latest packages. It went red due to some issues in the nextpnr environment. As soon as it goes green once again, I'll merge that and the nightly build will use the latest package.

> Is there a good place that displays the last N arch-defs git hashs that have run?

Currrently not, we can save this kind of information from somewhere though, (or add a symbiflow binary to the toolchain that can give us the version of the symbiflow-toolchain (from symbiflow-arch-defs). At the moment this information is available only in the name of the tarball.

**Comment by acomodi** [comment]
https://github.com/SymbiFlow/fpga-tool-perf/pull/290 Here is the tool-perf PR to add get autogenerated packages from arch-defs

**Comment by litghost** [comment]
> [SymbiFlow/fpga-tool-perf#290](https://github.com/SymbiFlow/fpga-tool-perf/pull/290) Here is the tool-perf PR to add get autogenerated packages from arch-defs

Ok, great!  I'll wait until a green nightly run, then merge this!

**Comment by acomodi** [comment]
> Ok, great! I'll wait until a green nightly run, then merge this!

So, there was a failure in the nightly run of one nextpnr-test, due to an out of memory issue (I believe there are too many parallel tests, I'll need to reduce the number of cores used).

Nevertheless, all the VPR data has been captured in the last run (https://colab.research.google.com/drive/1Ny5OZ06R1KVjDykrAQbR0vTsTyiTT1Q7?usp=sharing).

**Pull request merged**
