### PR TITLE
Prevent NULL tiles from mapping to phy_tile

### LINKED ISSUE #1538: Multiple mapped tiles when creating synth io tiles
Added a synth tile definition to the design.json as follows:
`        {
            "name": "dout[8]",
            "node": "INT_R_X23Y100/LH3",
            "pin": "H7",
            "wire": "INT_INTERFACE_R_X23Y100/INT_INTERFACE_LH3",
            "wires_outside_roi": [
            ]
        }
`

And building the synth tiles gives the following error:
`  File "/scratch/safe/butta/symbiflow-arch-defs.syn/xc/common/utils/prjxray_create_synth_tiles.py", line 26, in map_tile_to_vpr_coord
    assert len(mapped_tiles) == 1, tile
AssertionError: INT_INTERFACE_R_X23Y100
`
I know this is not a normal location used as a synth tile, but is this a location I should be able to place a synth tile?  Is mapping to multiple vpr coordinates the correct result in this situation or a bug?

Link to branch containing these changes: [synth-tile-errors](https://github.com/andrewb1999/symbiflow-arch-defs/tree/synth-tile-errors)

### PR DESCRIPTION
**Pull request by andrewb1999**
Signed-off-by: Andrew Butt <butta@seas.upenn.edu>

Prevent NULL tile types from mapping to a phy_tile in tile_map.  Fixes #1538 by preventing two logical tiles mapping to the same phy_tile for unsplit tiles.

### CODE REVIEW

**Comment by litghost** [comment]
```
Built target file_env_Miniconda3-py37_4.8.2-Linux-x86_64.sh
Built target file_env_conda_bin_conda
Built target conda
Built target conda_yapf
yapf needs to reformat /home/travis/build/SymbiFlow/symbiflow-arch-defs/xc/common/utils/prjxray_form_channels.py
CMakeFiles/check_python.dir/build.make:77: recipe for target 'CMakeFiles/check_python' failed
```

**Comment by litghost** [comment]
```
FAILED: cd /tmpfs/src/github/symbiflow-arch-defs-presubmit-install/build/xc/xc7/archs/zynq7/devices/xc7z010-virt && /usr/bin/cmake -E env PYTHONPATH=/tmpfs/src/github/symbiflow-arch-defs-presubmit-install/third_party/prjxray:/tmpfs/src/github/symbiflow-arch-defs-presubmit-install/utils /tmpfs/src/github/symbiflow-arch-defs-presubmit-install/build/env/conda/bin/python3 /tmpfs/src/github/symbiflow-arch-defs-presubmit-install/xc/common/utils/prjxray_arch_import.py --db_root /tmpfs/src/github/symbiflow-arch-defs-presubmit-install/third_party/prjxray-db/zynq7/ --part xc7z010clg400-1 --connection_database /tmpfs/src/github/symbiflow-arch-defs-presubmit-install/build/xc/xc7/archs/zynq7/devices/xc7z010-virt/channels.db --output-arch /tmpfs/src/github/symbiflow-arch-defs-presubmit-install/build/xc/xc7/archs/zynq7/devices/xc7z010-virt/arch.xml --tile-types CLBLL_L,CLBLL_R,CLBLM_L,CLBLM_R,BRAM_L,RIOPAD_M,RIOPAD_S,RIOPAD_SING,CLK_BUFG_TOP_R,CLK_BUFG_BOT_R,CMT_TOP_L_UPPER_T,HCLK_IOI3,PSS2 --pb_types SLICEL,SLICEM,BRAM_L,IOPAD,IOPAD_M,IOPAD_S,BUFGCTRL,PLLE2_ADV,HCLK_IOI3,PSS2 --pin_assignments /tmpfs/src/github/symbiflow-arch-defs-presubmit-install/build/xc/xc7/archs/zynq7/pin_assignments.json --device xc7z010

Loading database from '/tmpfs/src/github/symbiflow-arch-defs-presubmit-install/build/xc/xc7/archs/zynq7/devices/xc7z010-virt/channels.db'
No progressbar disabled because non-interactive terminal.
Traceback (most recent call last):
  File "/tmpfs/src/github/symbiflow-arch-defs-presubmit-install/xc/common/utils/prjxray_arch_import.py", line 1023, in <module>
    main()
  File "/tmpfs/src/github/symbiflow-arch-defs-presubmit-install/xc/common/utils/prjxray_arch_import.py", line 788, in main
    conn, model_xml, complexblocklist_xml, tiles_xml
  File "/tmpfs/src/github/symbiflow-arch-defs-presubmit-install/xc/common/utils/prjxray_arch_import.py", line 620, in insert_constant_tiles
    assert len(results) == 1, results
AssertionError: []
```

**Comment by litghost** [comment]
Maybe just filter NULL in the other lookup?

**Comment by andrewb1999** [comment]
> Maybe just filter NULL in the other lookup?

Yeah that seems reasonable.

**Pull request closed without merging**
