### PR TITLE
Add support for specifying version and build for conda packages

### PR DESCRIPTION
**Pull request by elmsfu**

### CODE REVIEW

**Comment by litghost** [comment]
Please add documentation for what this does and how to use it

**Comment by elmsfu** [comment]
Thanks @litghost Taking a closer look at the spec, I think an optional argument is more general and a better solution.

**Comment by litghost** [comment]
You brought in some submodule changes, revert?

**Comment by elmsfu** [comment]
> You brought in some submodule changes, revert?

nope. oops. will fix that.

**Pull request merged**
