### PR TITLE
Update VTR which fixes #491

### LINKED ISSUE #491: [XC7] Some designs fail on hardware
@mkurc came up with https://github.com/SymbiFlow/symbiflow-arch-defs/pull/490 that works at small N and fails at larger N.

This issue tracks the investigation into why this is happening and potential solutions.

### PR DESCRIPTION
**Pull request by litghost**

### CODE REVIEW

**Comment by mithro** [comment]
Any idea why yapf thinks it needs to reformat everything?

**Comment by mithro** [comment]
```
Scanning dependencies of target check_python
yapf needs to reformat /home/travis/build/SymbiFlow/symbiflow-arch-defs/ice40/utils/ice40_import_routing_from_icebox.py
yapf needs to reformat /home/travis/build/SymbiFlow/symbiflow-arch-defs/utils/lib/rr_graph/channel.py
yapf needs to reformat /home/travis/build/SymbiFlow/symbiflow-arch-defs/utils/lib/rr_graph/graph.py
yapf needs to reformat /home/travis/build/SymbiFlow/symbiflow-arch-defs/utils/lib/rr_graph/graph2.py
yapf needs to reformat /home/travis/build/SymbiFlow/symbiflow-arch-defs/utils/mux_gen.py
yapf needs to reformat /home/travis/build/SymbiFlow/symbiflow-arch-defs/xc7/utils/prjxray_assign_tile_pin_direction.py
yapf needs to reformat /home/travis/build/SymbiFlow/symbiflow-arch-defs/xc7/utils/prjxray_create_edges.py
```

**Comment by litghost** [comment]
> ```
> Scanning dependencies of target check_python
> yapf needs to reformat /home/travis/build/SymbiFlow/symbiflow-arch-defs/ice40/utils/ice40_import_routing_from_icebox.py
> yapf needs to reformat /home/travis/build/SymbiFlow/symbiflow-arch-defs/utils/lib/rr_graph/channel.py
> yapf needs to reformat /home/travis/build/SymbiFlow/symbiflow-arch-defs/utils/lib/rr_graph/graph.py
> yapf needs to reformat /home/travis/build/SymbiFlow/symbiflow-arch-defs/utils/lib/rr_graph/graph2.py
> yapf needs to reformat /home/travis/build/SymbiFlow/symbiflow-arch-defs/utils/mux_gen.py
> yapf needs to reformat /home/travis/build/SymbiFlow/symbiflow-arch-defs/xc7/utils/prjxray_assign_tile_pin_direction.py
> yapf needs to reformat /home/travis/build/SymbiFlow/symbiflow-arch-defs/xc7/utils/prjxray_create_edges.py
> ```

yapf version isn't pinned.  I'm going to update this PR with a pinned version.

**Comment by litghost** [comment]
Ya, yapf went from 0.26 to 0.27.  I've pinned it to 0.26.

**Pull request merged**
