### PR TITLE
Add FF-LUT pack patterns.

### PR DESCRIPTION
**Pull request by litghost**

### CODE REVIEW

**Review by mithro — COMMENTED** [review]
Any idea how was this working without these?

**Comment by litghost** [comment]
> Any idea how was this working without these?

These aren't required, they just help the packer to pack tighter, and results in some CPD improvements.

**Review by mkurc-ant — COMMENTED** [review]
Shouldn't these pack patterns have specialized names? Like "**A**LUT5_TO_FF_FDSE" ?

**Comment by litghost** [comment]
> Shouldn't these pack patterns have specialized names? Like "**A**LUT5_TO_FF_FDSE" ?

They specially should not be specialized.  pack pattern -> molecule happens pre cluster placement.

**Pull request merged**
