### PR TITLE
WIP: Update to latest prjxray-db (including all LiteX Arty bits).

### PR DESCRIPTION
**Pull request by litghost**
I expect some potential fasm2v breakages with this new database.

### CODE REVIEW

**Comment by mkurc-ant** [comment]
Besides fixing fasm2v stuff it is required to rebuild harness(es) so it contains new fasm tags.

**Comment by mithro** [comment]
@mkurc-ant - I rebuilt the harnesses in https://github.com/SymbiFlow/prjxray-db/commit/866e2271c183e73927d539e34f04dc7b2024f77e -- do they need another rebuild?

**Comment by mithro** [comment]
Looks like this is failing with;
```
prjxray.fasm_assembler.FasmLookupError: Segment DB LIOB33_SING, key LIOB33_SING.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'LIOB33_SING_X0Y0.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB LIOB33_SING, key LIOB33_SING.IOB_Y0.OSERDESE.DATA_RATE_TQ.BUF not found from line 'LIOB33_SING_X0Y0.IOB_Y0.OSERDESE.DATA_RATE_TQ.BUF'
Segment DB LIOB33_SING, key LIOB33_SING.IOB_Y0.SLEW.SLOW not found from line 'LIOB33_SING_X0Y0.IOB_Y0.SLEW.SLOW'
Segment DB LIOB33, key LIOB33.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'LIOB33_X0Y1.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB LIOB33, key LIOB33.IOB_Y0.OSERDESE.DATA_RATE_TQ.BUF not found from line 'LIOB33_X0Y1.IOB_Y0.OSERDESE.DATA_RATE_TQ.BUF'
Segment DB LIOB33, key LIOB33.IOB_Y0.SLEW.SLOW not found from line 'LIOB33_X0Y1.IOB_Y0.SLEW.SLOW'
Segment DB LIOB33, key LIOB33.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'LIOB33_X0Y1.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB LIOB33, key LIOB33.IOB_Y1.OSERDESE.DATA_RATE_TQ.BUF not found from line 'LIOB33_X0Y1.IOB_Y1.OSERDESE.DATA_RATE_TQ.BUF'
Segment DB LIOB33, key LIOB33.IOB_Y1.SLEW.SLOW not found from line 'LIOB33_X0Y1.IOB_Y1.SLEW.SLOW'
Segment DB LIOB33, key LIOB33.IOB_Y0.IN_ONLY not found from line 'LIOB33_X0Y11.IOB_Y0.IN_ONLY'
Segment DB LIOB33, key LIOB33.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'LIOB33_X0Y11.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB LIOB33, key LIOB33.IOB_Y0.SLEW.FAST not found from line 'LIOB33_X0Y11.IOB_Y0.SLEW.FAST'
Segment DB LIOB33, key LIOB33.IOB_Y0.ZINV_D not found from line 'LIOB33_X0Y11.IOB_Y0.ZINV_D'
Segment DB LIOB33, key LIOB33.IOB_Y1.IN_ONLY not found from line 'LIOB33_X0Y11.IOB_Y1.IN_ONLY'
Segment DB LIOB33, key LIOB33.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'LIOB33_X0Y11.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB LIOB33, key LIOB33.IOB_Y1.SLEW.FAST not found from line 'LIOB33_X0Y11.IOB_Y1.SLEW.FAST'
Segment DB LIOB33, key LIOB33.IOB_Y1.ZINV_D not found from line 'LIOB33_X0Y11.IOB_Y1.ZINV_D'
Segment DB LIOB33, key LIOB33.IOB_Y0.IN_ONLY not found from line 'LIOB33_X0Y111.IOB_Y0.IN_ONLY'
Segment DB LIOB33, key LIOB33.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'LIOB33_X0Y111.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB LIOB33, key LIOB33.IOB_Y0.SLEW.FAST not found from line 'LIOB33_X0Y111.IOB_Y0.SLEW.FAST'
Segment DB LIOB33, key LIOB33.IOB_Y0.ZINV_D not found from line 'LIOB33_X0Y111.IOB_Y0.ZINV_D'
Segment DB LIOB33, key LIOB33.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'LIOB33_X0Y111.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB LIOB33, key LIOB33.IOB_Y1.OSERDESE.DATA_RATE_TQ.BUF not found from line 'LIOB33_X0Y111.IOB_Y1.OSERDESE.DATA_RATE_TQ.BUF'
Segment DB LIOB33, key LIOB33.IOB_Y1.SLEW.SLOW not found from line 'LIOB33_X0Y111.IOB_Y1.SLEW.SLOW'
Segment DB LIOB33, key LIOB33.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'LIOB33_X0Y17.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB LIOB33, key LIOB33.IOB_Y0.OSERDESE.DATA_RATE_TQ.BUF not found from line 'LIOB33_X0Y17.IOB_Y0.OSERDESE.DATA_RATE_TQ.BUF'
Segment DB LIOB33, key LIOB33.IOB_Y0.SLEW.SLOW not found from line 'LIOB33_X0Y17.IOB_Y0.SLEW.SLOW'
Segment DB LIOB33, key LIOB33.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'LIOB33_X0Y17.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB LIOB33, key LIOB33.IOB_Y1.SLEW.FAST not found from line 'LIOB33_X0Y17.IOB_Y1.SLEW.FAST'
Segment DB LIOB33, key LIOB33.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'LIOB33_X0Y19.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB LIOB33, key LIOB33.IOB_Y0.OSERDESE.DATA_RATE_TQ.BUF not found from line 'LIOB33_X0Y19.IOB_Y0.OSERDESE.DATA_RATE_TQ.BUF'
Segment DB LIOB33, key LIOB33.IOB_Y0.SLEW.SLOW not found from line 'LIOB33_X0Y19.IOB_Y0.SLEW.SLOW'
Segment DB LIOB33, key LIOB33.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'LIOB33_X0Y19.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB LIOB33, key LIOB33.IOB_Y1.OSERDESE.DATA_RATE_TQ.BUF not found from line 'LIOB33_X0Y19.IOB_Y1.OSERDESE.DATA_RATE_TQ.BUF'
Segment DB LIOB33, key LIOB33.IOB_Y1.SLEW.SLOW not found from line 'LIOB33_X0Y19.IOB_Y1.SLEW.SLOW'
Segment DB LIOB33, key LIOB33.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'LIOB33_X0Y3.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB LIOB33, key LIOB33.IOB_Y0.OSERDESE.DATA_RATE_TQ.BUF not found from line 'LIOB33_X0Y3.IOB_Y0.OSERDESE.DATA_RATE_TQ.BUF'
Segment DB LIOB33, key LIOB33.IOB_Y0.SLEW.SLOW not found from line 'LIOB33_X0Y3.IOB_Y0.SLEW.SLOW'
Segment DB LIOB33, key LIOB33.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'LIOB33_X0Y3.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB LIOB33, key LIOB33.IOB_Y1.OSERDESE.DATA_RATE_TQ.BUF not found from line 'LIOB33_X0Y3.IOB_Y1.OSERDESE.DATA_RATE_TQ.BUF'
Segment DB LIOB33, key LIOB33.IOB_Y1.SLEW.SLOW not found from line 'LIOB33_X0Y3.IOB_Y1.SLEW.SLOW'
Segment DB LIOB33, key LIOB33.IOB_Y0.IN_ONLY not found from line 'LIOB33_X0Y43.IOB_Y0.IN_ONLY'
Segment DB LIOB33, key LIOB33.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'LIOB33_X0Y43.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB LIOB33, key LIOB33.IOB_Y0.SLEW.FAST not found from line 'LIOB33_X0Y43.IOB_Y0.SLEW.FAST'
Segment DB LIOB33, key LIOB33.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'LIOB33_X0Y43.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB LIOB33, key LIOB33.IOB_Y1.OSERDESE.DATA_RATE_TQ.BUF not found from line 'LIOB33_X0Y43.IOB_Y1.OSERDESE.DATA_RATE_TQ.BUF'
Segment DB LIOB33, key LIOB33.IOB_Y1.SLEW.SLOW not found from line 'LIOB33_X0Y43.IOB_Y1.SLEW.SLOW'
Segment DB LIOB33, key LIOB33.IOB_Y0.IN_ONLY not found from line 'LIOB33_X0Y5.IOB_Y0.IN_ONLY'
Segment DB LIOB33, key LIOB33.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'LIOB33_X0Y5.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB LIOB33, key LIOB33.IOB_Y0.SLEW.FAST not found from line 'LIOB33_X0Y5.IOB_Y0.SLEW.FAST'
Segment DB LIOB33, key LIOB33.IOB_Y0.ZINV_D not found from line 'LIOB33_X0Y5.IOB_Y0.ZINV_D'
Segment DB LIOB33, key LIOB33.IOB_Y1.IN_ONLY not found from line 'LIOB33_X0Y5.IOB_Y1.IN_ONLY'
Segment DB LIOB33, key LIOB33.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'LIOB33_X0Y5.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB LIOB33, key LIOB33.IOB_Y1.SLEW.FAST not found from line 'LIOB33_X0Y5.IOB_Y1.SLEW.FAST'
Segment DB LIOB33, key LIOB33.IOB_Y1.ZINV_D not found from line 'LIOB33_X0Y5.IOB_Y1.ZINV_D'
Segment DB LIOB33, key LIOB33.IOB_Y0.IN_ONLY not found from line 'LIOB33_X0Y7.IOB_Y0.IN_ONLY'
Segment DB LIOB33, key LIOB33.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'LIOB33_X0Y7.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB LIOB33, key LIOB33.IOB_Y0.SLEW.FAST not found from line 'LIOB33_X0Y7.IOB_Y0.SLEW.FAST'
Segment DB LIOB33, key LIOB33.IOB_Y0.ZINV_D not found from line 'LIOB33_X0Y7.IOB_Y0.ZINV_D'
Segment DB LIOB33, key LIOB33.IOB_Y1.IN_ONLY not found from line 'LIOB33_X0Y7.IOB_Y1.IN_ONLY'
Segment DB LIOB33, key LIOB33.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'LIOB33_X0Y7.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB LIOB33, key LIOB33.IOB_Y1.SLEW.FAST not found from line 'LIOB33_X0Y7.IOB_Y1.SLEW.FAST'
Segment DB LIOB33, key LIOB33.IOB_Y1.ZINV_D not found from line 'LIOB33_X0Y7.IOB_Y1.ZINV_D'
Segment DB LIOB33, key LIOB33.IOB_Y0.IN_ONLY not found from line 'LIOB33_X0Y9.IOB_Y0.IN_ONLY'
Segment DB LIOB33, key LIOB33.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'LIOB33_X0Y9.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB LIOB33, key LIOB33.IOB_Y0.SLEW.FAST not found from line 'LIOB33_X0Y9.IOB_Y0.SLEW.FAST'
Segment DB LIOB33, key LIOB33.IOB_Y0.ZINV_D not found from line 'LIOB33_X0Y9.IOB_Y0.ZINV_D'
Segment DB LIOB33, key LIOB33.IOB_Y1.IN_ONLY not found from line 'LIOB33_X0Y9.IOB_Y1.IN_ONLY'
Segment DB LIOB33, key LIOB33.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'LIOB33_X0Y9.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB LIOB33, key LIOB33.IOB_Y1.SLEW.FAST not found from line 'LIOB33_X0Y9.IOB_Y1.SLEW.FAST'
Segment DB LIOB33, key LIOB33.IOB_Y1.ZINV_D not found from line 'LIOB33_X0Y9.IOB_Y1.ZINV_D'
Segment DB RIOB33, key RIOB33.IOB_Y0.IN_ONLY not found from line 'RIOB33_X43Y25.IOB_Y0.IN_ONLY'
Segment DB RIOB33, key RIOB33.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'RIOB33_X43Y25.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB RIOB33, key RIOB33.IOB_Y0.SLEW.FAST not found from line 'RIOB33_X43Y25.IOB_Y0.SLEW.FAST'
Segment DB RIOB33, key RIOB33.IOB_Y0.ZINV_D not found from line 'RIOB33_X43Y25.IOB_Y0.ZINV_D'
Segment DB RIOB33, key RIOB33.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'RIOB33_X43Y25.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB RIOB33, key RIOB33.IOB_Y1.SLEW.FAST not found from line 'RIOB33_X43Y25.IOB_Y1.SLEW.FAST'
Segment DB RIOB33, key RIOB33.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'RIOB33_X43Y31.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB RIOB33, key RIOB33.IOB_Y0.OSERDESE.DATA_RATE_TQ.BUF not found from line 'RIOB33_X43Y31.IOB_Y0.OSERDESE.DATA_RATE_TQ.BUF'
Segment DB RIOB33, key RIOB33.IOB_Y0.SLEW.SLOW not found from line 'RIOB33_X43Y31.IOB_Y0.SLEW.SLOW'
Segment DB RIOB33, key RIOB33.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'RIOB33_X43Y31.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB RIOB33, key RIOB33.IOB_Y1.SLEW.FAST not found from line 'RIOB33_X43Y31.IOB_Y1.SLEW.FAST'
Segment DB RIOB33, key RIOB33.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'RIOB33_X43Y37.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB RIOB33, key RIOB33.IOB_Y0.OSERDESE.DATA_RATE_TQ.BUF not found from line 'RIOB33_X43Y37.IOB_Y0.OSERDESE.DATA_RATE_TQ.BUF'
Segment DB RIOB33, key RIOB33.IOB_Y0.SLEW.SLOW not found from line 'RIOB33_X43Y37.IOB_Y0.SLEW.SLOW'
Segment DB RIOB33, key RIOB33.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'RIOB33_X43Y37.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB RIOB33, key RIOB33.IOB_Y1.OSERDESE.DATA_RATE_TQ.BUF not found from line 'RIOB33_X43Y37.IOB_Y1.OSERDESE.DATA_RATE_TQ.BUF'
Segment DB RIOB33, key RIOB33.IOB_Y1.SLEW.SLOW not found from line 'RIOB33_X43Y37.IOB_Y1.SLEW.SLOW'
Segment DB RIOB33, key RIOB33.IOB_Y0.IN_ONLY not found from line 'RIOB33_X43Y39.IOB_Y0.IN_ONLY'
Segment DB RIOB33, key RIOB33.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'RIOB33_X43Y39.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB RIOB33, key RIOB33.IOB_Y0.SLEW.FAST not found from line 'RIOB33_X43Y39.IOB_Y0.SLEW.FAST'
Segment DB RIOB33, key RIOB33.IOB_Y0.ZINV_D not found from line 'RIOB33_X43Y39.IOB_Y0.ZINV_D'
Segment DB RIOB33, key RIOB33.IOB_Y1.IN_ONLY not found from line 'RIOB33_X43Y39.IOB_Y1.IN_ONLY'
Segment DB RIOB33, key RIOB33.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'RIOB33_X43Y39.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB RIOB33, key RIOB33.IOB_Y1.SLEW.FAST not found from line 'RIOB33_X43Y39.IOB_Y1.SLEW.FAST'
Segment DB RIOB33, key RIOB33.IOB_Y1.ZINV_D not found from line 'RIOB33_X43Y39.IOB_Y1.ZINV_D'
Segment DB RIOB33, key RIOB33.IOB_Y0.IN_ONLY not found from line 'RIOB33_X43Y43.IOB_Y0.IN_ONLY'
Segment DB RIOB33, key RIOB33.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'RIOB33_X43Y43.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB RIOB33, key RIOB33.IOB_Y0.SLEW.FAST not found from line 'RIOB33_X43Y43.IOB_Y0.SLEW.FAST'
Segment DB RIOB33, key RIOB33.IOB_Y0.ZINV_D not found from line 'RIOB33_X43Y43.IOB_Y0.ZINV_D'
Segment DB RIOB33, key RIOB33.IOB_Y1.IN_ONLY not found from line 'RIOB33_X43Y43.IOB_Y1.IN_ONLY'
Segment DB RIOB33, key RIOB33.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'RIOB33_X43Y43.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB RIOB33, key RIOB33.IOB_Y1.SLEW.FAST not found from line 'RIOB33_X43Y43.IOB_Y1.SLEW.FAST'
Segment DB RIOB33, key RIOB33.IOB_Y1.ZINV_D not found from line 'RIOB33_X43Y43.IOB_Y1.ZINV_D'
Segment DB RIOB33, key RIOB33.IOB_Y0.IN_ONLY not found from line 'RIOB33_X43Y45.IOB_Y0.IN_ONLY'
Segment DB RIOB33, key RIOB33.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'RIOB33_X43Y45.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB RIOB33, key RIOB33.IOB_Y0.SLEW.FAST not found from line 'RIOB33_X43Y45.IOB_Y0.SLEW.FAST'
Segment DB RIOB33, key RIOB33.IOB_Y0.ZINV_D not found from line 'RIOB33_X43Y45.IOB_Y0.ZINV_D'
Segment DB RIOB33, key RIOB33.IOB_Y1.IN_ONLY not found from line 'RIOB33_X43Y45.IOB_Y1.IN_ONLY'
Segment DB RIOB33, key RIOB33.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'RIOB33_X43Y45.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB RIOB33, key RIOB33.IOB_Y1.SLEW.FAST not found from line 'RIOB33_X43Y45.IOB_Y1.SLEW.FAST'
Segment DB RIOB33, key RIOB33.IOB_Y1.ZINV_D not found from line 'RIOB33_X43Y45.IOB_Y1.ZINV_D'
Segment DB RIOB33, key RIOB33.IOB_Y0.IN_ONLY not found from line 'RIOB33_X43Y47.IOB_Y0.IN_ONLY'
Segment DB RIOB33, key RIOB33.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'RIOB33_X43Y47.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB RIOB33, key RIOB33.IOB_Y0.SLEW.FAST not found from line 'RIOB33_X43Y47.IOB_Y0.SLEW.FAST'
Segment DB RIOB33, key RIOB33.IOB_Y0.ZINV_D not found from line 'RIOB33_X43Y47.IOB_Y0.ZINV_D'
Segment DB RIOB33, key RIOB33.IOB_Y1.IN_ONLY not found from line 'RIOB33_X43Y47.IOB_Y1.IN_ONLY'
Segment DB RIOB33, key RIOB33.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'RIOB33_X43Y47.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB RIOB33, key RIOB33.IOB_Y1.SLEW.FAST not found from line 'RIOB33_X43Y47.IOB_Y1.SLEW.FAST'
Segment DB RIOB33, key RIOB33.IOB_Y1.ZINV_D not found from line 'RIOB33_X43Y47.IOB_Y1.ZINV_D'
Segment DB RIOB33, key RIOB33.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'RIOB33_X43Y61.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB RIOB33, key RIOB33.IOB_Y0.SLEW.FAST not found from line 'RIOB33_X43Y61.IOB_Y0.SLEW.FAST'
Segment DB RIOB33, key RIOB33.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'RIOB33_X43Y61.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB RIOB33, key RIOB33.IOB_Y1.OSERDESE.DATA_RATE_TQ.BUF not found from line 'RIOB33_X43Y61.IOB_Y1.OSERDESE.DATA_RATE_TQ.BUF'
Segment DB RIOB33, key RIOB33.IOB_Y1.SLEW.SLOW not found from line 'RIOB33_X43Y61.IOB_Y1.SLEW.SLOW'
Segment DB RIOB33, key RIOB33.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'RIOB33_X43Y75.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB RIOB33, key RIOB33.IOB_Y0.OSERDESE.DATA_RATE_TQ.BUF not found from line 'RIOB33_X43Y75.IOB_Y0.OSERDESE.DATA_RATE_TQ.BUF'
Segment DB RIOB33, key RIOB33.IOB_Y0.SLEW.SLOW not found from line 'RIOB33_X43Y75.IOB_Y0.SLEW.SLOW'
Segment DB RIOB33, key RIOB33.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'RIOB33_X43Y75.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB RIOB33, key RIOB33.IOB_Y1.OSERDESE.DATA_RATE_TQ.BUF not found from line 'RIOB33_X43Y75.IOB_Y1.OSERDESE.DATA_RATE_TQ.BUF'
Segment DB RIOB33, key RIOB33.IOB_Y1.SLEW.SLOW not found from line 'RIOB33_X43Y75.IOB_Y1.SLEW.SLOW'
Segment DB RIOB33, key RIOB33.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'RIOB33_X43Y87.IOB_Y0.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB RIOB33, key RIOB33.IOB_Y0.SLEW.FAST not found from line 'RIOB33_X43Y87.IOB_Y0.SLEW.FAST'
Segment DB RIOB33, key RIOB33.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE not found from line 'RIOB33_X43Y87.IOB_Y1.ODDR.DDR_CLK_EDGE.OPPOSITE_EDGE'
Segment DB RIOB33, key RIOB33.IOB_Y1.OSERDESE.DATA_RATE_TQ.BUF not found from line 'RIOB33_X43Y87.IOB_Y1.OSERDESE.DATA_RATE_TQ.BUF'
Segment DB RIOB33, key RIOB33.IOB_Y1.SLEW.SLOW not found from line 'RIOB33_X43Y87.IOB_Y1.SLEW.SLOW'
xc7/tests/dram/CMakeFiles/dram_1_32m_bin.dir/build.make:66: recipe for target 'xc7/tests/dram/dram_1_32m/artix7-xc7a50t-basys3-roi-virt-xc7a50t-basys3-test/top.frames' failed
make[3]: *** [xc7/tests/dram/dram_1_32m/artix7-xc7a50t-basys3-roi-virt-xc7a50t-basys3-test/top.frames] Error 1
make[3]: *** Deleting file 'xc7/tests/dram/dram_1_32m/artix7-xc7a50t-basys3-roi-virt-xc7a50t-basys3-test/top.frames'
CMakeFiles/Makefile2:86443: recipe for target 'xc7/tests/dram/CMakeFiles/dram_1_32m_bin.dir/all' failed
make[2]: *** [xc7/tests/dram/CMakeFiles/dram_1_32m_bin.dir/all] Error 2
CMakeFiles/Makefile2:142: recipe for target 'CMakeFiles/all_xc7.dir/rule' failed
make[1]: *** [CMakeFiles/all_xc7.dir/rule] Error 2
Makefile:199: recipe for target 'all_xc7' failed
make: *** [all_xc7] Error 2
[ID: 2829423] Build finished after 5095 secs, exit value: 1
```

**Comment by mithro** [comment]
I think the pull request at https://github.com/SymbiFlow/symbiflow-arch-defs/pull/936 replaces this one?

**Comment by mkurc-ant** [comment]
@mithro Yep, I figured that out too. Today I tried and with db from 866e227 everything works fine.

**Pull request closed without merging**
