### PR TITLE
Add target to use yapf to check all python files

### PR DESCRIPTION
**Pull request by elmsfu**

### CODE REVIEW

**Comment by litghost** [comment]
Should we just add the start of the make format target too?

**Comment by elmsfu** [comment]
> Should we just add the start of the make format target too?

I don't understand what you are suggesting. Can you clarify? a link or suggestion would help.

**Comment by litghost** [comment]
> > Should we just add the start of the make format target too?
> 
> I don't understand what you are suggesting. Can you clarify? a link or suggestion would help.

In prjxray, this check is implemented as:
make format
git diff 
if $? != 0 -> needs format

https://github.com/SymbiFlow/prjxray/blob/master/Makefile#L62

I believe yapf -i is "update file in place".

Anyways, I like the idea of a check format target (good for pre-push hooks), but the more important target is "make format", e.g. the thing that will fix the formatting.

**Comment by mithro** [comment]
Do we already have a yapf config file?
We use the following file for [Project X-Ray](https://github.com/SymbiFlow/prjxray/blob/master/.style.yapf)

**Comment by elmsfu** [comment]
> Do we already have a yapf config file?
> We use the following file for [Project X-Ray](https://github.com/SymbiFlow/prjxray/blob/master/.style.yapf)

I don't see one anywhere. I can use the same style and add that to #522

**Comment by mithro** [comment]
Let's add the config file.

**Comment by mithro** [comment]
DCO.

**Pull request merged**
