### PR TITLE
xc/xc7/yosys: add multiple XDCs support

### PR DESCRIPTION
**Pull request by kowalewskijan**
Included changes:
- [x] add a test case for multiple XDCs design ([multixdc_counter](https://github.com/SymbiFlow/symbiflow-arch-defs/pull/2133/files#diff-7acd4c824283141ea1d0e3655e5bf9a3890d72d9e0fef84a4bca55d18b9878fd))
- [x] rename `INPUT_XDC_FILE` to `INPUT_XDC_FILES` and rework this variable to be a list

Signed-off-by: Jan Kowalewski <jkowalewski@antmicro.com>

### CODE REVIEW

**Review by acomodi — COMMENTED** [review]
LGTM.

I'd add a comment on the fact that this solves multiple XDCs.
Probably a test to verify this is working as expected might be worth adding.

**Comment by mithro** [comment]
Yes, please add a test.

**Review by tmichalak — APPROVED** [review]
LGTM, provided you add the test.

**Review by acomodi — APPROVED** [review]
LGTM, merging

**Pull request merged**
