### PR TITLE
Add explicit CEUSEDMUX and SRUSEDMUX support.

### PR DESCRIPTION
**Pull request by litghost**
This has been tested with https://github.com/SymbiFlow/symbiflow-arch-defs/pull/575

### CODE REVIEW

**Comment by litghost** [comment]
This breaks on non-trival examples, investigating.

**Comment by litghost** [comment]
> This breaks on non-trival examples, investigating.

Looks like pack patterns were required, but they are nasty.  I'll commit the "working" version, and begin thinking about how to make the pack pattern generation suck less.

**Comment by litghost** [comment]
> > This breaks on non-trival examples, investigating.
> 
> Looks like pack patterns were required, but they are nasty. I'll commit the "working" version, and begin thinking about how to make the pack pattern generation suck less.

Using pack patterns solves the packing issue at the cost of the typical VPR packing problem, which is that it no longer packs a tightly.  Investigating ...

**Comment by mithro** [comment]
The pack pattern is a be horrific but otherwise looks okay I think?

**Comment by litghost** [comment]
> The pack pattern is a be horrific but otherwise looks okay I think?

Amazingly the CI shows green, so that means murax pack/placed/routed!  I want to make those pack patterns generated (rather than hand written), and I also need to verify resource usage.  It's unclear if VPR can pack all 8 FF's into a SLICE any more with this PR.

**Comment by mkurc-ant** [comment]
@litghost So with this PR the VPR will be able to use `VCC` and `GND` local to `CEUSEDMUX` and `SEUSEDMUX` ?

BTW I like the comment "... to make the pack pattern generation suck less" ;)

**Comment by litghost** [comment]
> @litghost So with this PR the VPR will be able to use `VCC` and `GND` local to `CEUSEDMUX` and `SEUSEDMUX` ?

Exactly!

**Comment by litghost** [comment]
Using https://github.com/SymbiFlow/symbiflow-arch-defs/pull/591 I've determined that this PR does need increase sum CLB usage for any of the basys3 test bitstreams.  Given that, I'll focus on making the pack pattern output be less terrible.  This is probably a good time to migrate to v2x, and hopefully I can compactly express the required pack pattern there without too much trouble using generate statements.

**Comment by litghost** [comment]
> Using #591 I've determined that this PR does need increase sum CLB usage for any of the basys3 test bitstreams. Given that, I'll focus on making the pack pattern output be less terrible. This is probably a good time to migrate to v2x, and hopefully I can compactly express the required pack pattern there without too much trouble using generate statements.

https://gist.github.com/litghost/5208eb5304e441cd281ec08aa4a0c975 has the data in CSV format.  Data points:
- ff_pack: Results from this PR
- no_ff_pack: Results from master
- round_robin_ff_pack: Results from this PR with round robin turned on

**Pull request merged**
