### PR TITLE
Retry marking CARRY4_VPR as whitebox

### PR DESCRIPTION
**Pull request by Arvind-Srinivasan**
Rebased a PR (https://github.com/SymbiFlow/symbiflow-arch-defs/pull/2082) previously made by Dan Ravensloft

Signed-off-by: Dan Ravensloft <dan.ravensloft@gmail.com>

### CODE REVIEW

**Comment by litghost** [comment]
I don't have a problem with trying, but what changed such that we expect this to return a different result?

**Comment by Arvind-Srinivasan** [comment]
My understanding was there would be an install issue which would cause CI to fail otherwise.

**Comment by litghost** [comment]
> My understanding was there would be an install issue which would cause CI to fail otherwise.

I believe last time we tried this it caused an "as expected" packing issue.  The solution was then to remove the black/whitebox completely so that the cell was opaque to abc.  This resulted in a smaller negative (or eligible) CPD impact, and was merged.

**Comment by Arvind-Srinivasan** [comment]
My bad, then I will close.

**Pull request closed without merging**
