### PR TITLE
Add RAM64M

### PR DESCRIPTION
**Pull request by HackerFoo**
Merge after #678

### CODE REVIEW

**Comment by litghost** [comment]
Please merge with master

**Comment by mithro** [comment]
@litghost Do you mean rebase?

**Comment by litghost** [comment]
> @litghost Do you mean rebase?

Either is fine with me.

**Comment by HackerFoo** [comment]
> LGTM, but CI is red?

```
CondaHTTPError: HTTP 504 GATEWAY_TIMEOUT for url <https://conda.anaconda.org/m-labs/linux-64/repodata.json>
Elapsed: 00:59.351789
```

**Pull request merged**
