### PR TITLE
Add ibex test for Nexys Video

### PR DESCRIPTION
**Pull request by rw1nkler**
This PR adds the Ibex test for a Nexys Video board. 
In the next step, I will integrate `sv2v` into the building system and convert Ibex directly from SystemVerilog sources.

The test passes `diff_fasm` step successfully. The generated bitstream works on hardware.

### CODE REVIEW

**Comment by litghost** [comment]
Looks like the ibex test didn't get built in the CI, looks like your need to updated: https://github.com/SymbiFlow/symbiflow-arch-defs/blob/6ec8e2045218b9e556dba3b6dfcab25998ba16c7/CMakeLists.txt#L197

**Comment by litghost** [comment]
Something is going wrong!  Checkout the routing log:
```
## Initializing router criticalities took 0.09 seconds (max_rss 11224.4 MiB, delta_rss +0.0 MiB)
---- ------ ------- ---- ------- ------- ------- ----------------- --------------- -------- ---------- ---------- ---------- ---------- --------
Iter   Time    pres  BBs    Heap  Re-Rtd  Re-Rtd Overused RR Nodes      Wirelength      CPD       sTNS       sWNS       hTNS       hWNS Est Succ
      (sec)     fac Updt    push    Nets   Conns                                       (ns)       (ns)       (ns)       (ns)       (ns)     Iter
---- ------ ------- ---- ------- ------- ------- ----------------- --------------- -------- ---------- ---------- ---------- ---------- --------
Warning 67: 3 timing startpoints were not constrained during timing analysis
Warning 68: 8913 timing endpoints were not constrained during timing analysis
   1   34.5     0.0    0 2.7e+08    6886   26092   25979 ( 0.261%) 1043205 ( 4.9%)      nan      0.000      0.000      0.000      0.000      N/A
   2    9.6     4.0    5 5.1e+07    4196   19700    3555 ( 0.036%) 1110834 ( 5.2%)      nan      0.000      0.000      0.000      0.000      N/A
   3    5.2     5.2   20 2.5e+07    2068   11428    1359 ( 0.014%) 1136559 ( 5.4%)      nan      0.000      0.000      0.000      0.000      N/A
   4    2.6     6.8   25 1.1e+07     914    5979     223 ( 0.002%) 1151696 ( 5.4%)      nan      0.000      0.000      0.000      0.000      N/A
   5    0.7     8.8    9 2508724     208    1561      20 ( 0.000%) 1155395 ( 5.4%)      nan      0.000      0.000      0.000      0.000      N/A
   6    0.3    11.4    4  415096      21     224       0 ( 0.000%) 1155697 ( 5.4%)      nan      0.000      0.000      0.000      0.000      N/A
Restoring best routing
Critical path: nan ns
```

**Comment by rw1nkler** [comment]
Hmm, the same thing happens for ibex on Arty, even without this PR. I will try to fix this.

**Comment by litghost** [comment]
> Hmm, the same thing happens for ibex on Arty, even without this PR. I will try to fix this.

This likely points out a latent bug in the timing graph.

**Comment by litghost** [comment]
Thanks, looks better now.

**Pull request merged**
