### PR TITLE
[DNM][WIP] Use Yosys to generate blif in v2x tests

### PR DESCRIPTION
**Pull request by kgugala**
This is PR is to discuss the VPR issues discovered when attempting to pack the test circuit to the arch generated basing on the pb_type xmls (see  #755 ) 

This PR is based on #645, but only one test is enabled. Also the flow has been modified to use Yosys for blif generation and the ` update_test_eblif.py`  script to transofr the yosys generated blif to a form expected by the test arch.

Once the issues in this PR are resolved, we can close it and cherry-pick the solution to #645

### CODE REVIEW

**Comment by kgugala** [comment]
@litghost @mithro this is the code to trigger #755. To reproduce:

clone
```
make env -j`nproc`
cd build/utils/vlog/tests/multiple_instance
make test_multiple_instance
```

**Comment by mithro** [comment]
@kgugala What is the status of this pull request? I think using Yosys to generate the eblif is a pretty good idea (verses using the current method).

**Comment by kgugala** [comment]
@mithro I think #755 is still not solved. @acomodi can you take a look on that?

**Comment by acomodi** [comment]
@kgugala @mithro Yes, I'll look into it

**Comment by kgugala** [comment]
work done here is included in #703. We can close this one

**Pull request closed without merging**
