### PR TITLE
brams: fix VCC fan bounce issue

### PR DESCRIPTION
**Pull request by acomodi**
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>

This PR should fix https://github.com/SymbiFlow/symbiflow-arch-defs/issues/1400

### CODE REVIEW

**Comment by kgugala** [comment]
now it fails in `fasm2bels` with:

```  
File "/tmpfs/src/github/symbiflow-arch-defs-presubmit-xc7-vendor/xc/xc7/fasm2bels/verilog_modeling.py", line 1685, in find_sources_from_sink
    wire_pkey = site.site_wire_to_wire_pkey[site_wire]
KeyError: 'REGCLKBL'
```

**Comment by acomodi** [comment]
> now it fails in `fasm2bels` with:
> 
> ```
> File "/tmpfs/src/github/symbiflow-arch-defs-presubmit-xc7-vendor/xc/xc7/fasm2bels/verilog_modeling.py", line 1685, in find_sources_from_sink
>     wire_pkey = site.site_wire_to_wire_pkey[site_wire]
> KeyError: 'REGCLKBL'
> ```

Fixed, CI should turn green now.

**Comment by acomodi** [comment]
The FAN_BOUNCE issue seems to be solved, but now the https://github.com/SymbiFlow/symbiflow-arch-defs/issues/1429 has reappeared.

**Comment by acomodi** [comment]
The IO placement issue does not appear when using https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1545. This because the placement step is not performed.

**Comment by litghost** [comment]
> The IO placement issue does not appear when using #1545. This because the placement step is not performed.

The problem still exists, in that it appears the clock placement script isn't taking into account BUFR/BUFIO/BUFMR <-> input as it should.

**Comment by acomodi** [comment]
@litghost Agreed, the problem though is that we do not make use of any of those BUFIO/BUFR and BUFMRs. Unsure how the solution would look like.

On a side note, also the full Vivado flow does not implement those clock tiles.

**Pull request merged**
