### PR TITLE
Fix remaining known issues with bitstream generation for xc7

### PR DESCRIPTION
**Pull request by litghost**
This fixes several unknown bits or diff FASM errors around OSERDES and BRAM.

Fixes https://github.com/SymbiFlow/symbiflow-arch-defs/issues/1536

### CODE REVIEW

**Comment by litghost** [comment]
I've added the needed fixes for the `_ACTIVE` features.

**Comment by litghost** [comment]
In theory this will go green!  Once we have a new database from https://github.com/SymbiFlow/prjxray/pull/1466, we can turn on `--verbose` for the diff fasm tests!

**Comment by litghost** [comment]
Looks like the new BRAM36 feature is inconsistently enabled.  Working on tracking down the pattern.  I might end up renaming it once I figure it out.

**Comment by litghost** [comment]
> Looks like the new BRAM36 feature is inconsistently enabled. Working on tracking down the pattern. I might end up renaming it once I figure it out.

I've figured out what is going on here.  I need to fix the new BRAM features, PR is going up soon on prjxray to fix the feature.

**Comment by litghost** [comment]
> > Looks like the new BRAM36 feature is inconsistently enabled. Working on tracking down the pattern. I might end up renaming it once I figure it out.
> 
> I've figured out what is going on here. I need to fix the new BRAM features, PR is going up soon on prjxray to fix the feature.

Fixes are up in:
 - https://github.com/SymbiFlow/prjxray/pull/1474
 - https://github.com/SymbiFlow/symbiflow-xc-fasm2bels/pull/35

Waiting for upstream changes to propagate and be merged, and I'll update this PR.

**Comment by litghost** [comment]
CI is green, please review

**Review by mkurc-ant — APPROVED** [review]
Ok, LGTM

**Pull request merged**
