### PR TITLE
WIP: added script to add tiles tag and equivalent tiles

### PR DESCRIPTION
**Pull request by acomodi**
This PR is an initial effort to change the XML structure and move the tile-specific tags from the top level `pb_types` to the `tiles` tag (solving https://github.com/SymbiFlow/symbiflow-arch-defs/issues/582).

Moreover, the script automatically tries to add the equivalent tiles specified by the user (right now their specification is hard-coded in the script).

Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>

### CODE REVIEW

**Comment by mithro** [comment]
@acomodi You'll need to update the XML schema here -> https://github.com/SymbiFlow/symbiflow-arch-defs/blob/master/common/xml/fpga_architecture.xsd

**Comment by mithro** [comment]
The [xmlsort.xsl](https://github.com/SymbiFlow/symbiflow-arch-defs/blob/master/common/xml/xmlsort.xsl) script is already use to "post process" the XML we have. Maybe it could be used for doing the XML rewriting too?

**Comment by litghost** [comment]
CI is reporting errors on all architectures.

**Comment by litghost** [comment]
@acomodi In the case of xc7, the arch file is generated.  Why not modify the way it is generated?  And for ice40 and testarch, use this method as it option on define_arch?

**Comment by acomodi** [comment]
So, I should modify the initial generation of the arch.xml, instead of manipulating it afterwards, right?

**Comment by litghost** [comment]
> So, I should modify the initial generation of the arch.xml, instead of manipulating it afterwards, right?

For xc7, yes.  That also solves the hard coding of the equivilance in the manipulation script.  For reasons that you've already stated, having a generic arch.old.xml to arch.new.xml is required for VPR to merge the tile change, so we need to develop that tool anyways.  It can be used on ice40 and testarch for now.

**Comment by acomodi** [comment]
All right, I will proceed by deleting the `equivalent tile` part from this script and leave only the swap from top level `pb_type` to `tiles` and add it as a dependency option for ice40 and testarch.
Then I'll create another PR with the modifications for the xc7 architectures

**Comment by litghost** [comment]
@acomodi I think we can close this PR?

**Comment by acomodi** [comment]
@litghost Yep, closing

**Pull request closed without merging**
